import {detectPitch,noteInfo,noteNames} from './pitch.js';
const $=id=>document.getElementById(id),presets={standard:[40,45,50,55,59,64],dropd:[38,45,50,55,59,64],flat:[39,44,49,54,58,63]};
let context,stream,analyser,timer,wake,locked=null,history=[],running=false,lastGood=0;
const read=(key,fallback)=>{try{return localStorage.getItem(key)||fallback}catch{return fallback}};
const save=(key,value)=>{try{localStorage.setItem(key,value)}catch{}};
$('tuning').value=read('six-tuning','standard');if(!$('tuning').value)$('tuning').value='standard';
$('reference').value=read('six-reference','440');if(!$('reference').value)$('reference').value='440';
function renderStrings(){const notes=presets[$('tuning').value];$('strings').replaceChildren();$('strings').hidden=!notes;$('auto').hidden=!notes;if(notes)notes.forEach((m,i)=>{const b=document.createElement('button');b.className='string'+(locked===i?' active':'');b.innerHTML=`<small>${6-i} 弦</small><strong>${noteNames[m%12]}</strong>`;b.setAttribute('aria-pressed',String(locked===i));b.onclick=()=>{locked=locked===i?null:i;history=[];renderStrings();};$('strings').append(b)});$('auto').classList.toggle('active',locked===null);$('mode').textContent=locked===null?(notes?'自动识别琴弦':'自由调音'):`锁定 ${6-locked} 弦`;}
function clearReading(){ $('note').innerHTML='—<small id="octave"></small>';$('frequency').textContent='— Hz';$('reading').textContent=running?'拨响一根琴弦':'准备好，拨响一根琴弦';$('needle').style.left='50%';$('needle').style.opacity='.4';document.querySelector('.display').classList.remove('in-tune');history=[];if(locked===null)document.querySelectorAll('.string').forEach(b=>b.classList.remove('active')); }
$('auto').onclick=()=>{locked=null;history=[];renderStrings()};
$('tuning').onchange=()=>{locked=null;save('six-tuning',$('tuning').value);clearReading();renderStrings()};$('reference').onchange=()=>{save('six-reference',$('reference').value);history=[]};
async function devices(){if(!navigator.mediaDevices?.enumerateDevices)return;const selected=$('input').value;const list=await navigator.mediaDevices.enumerateDevices();$('input').replaceChildren(new Option('系统默认麦克风',''));list.filter(d=>d.kind==='audioinput').forEach((d,i)=>$('input').add(new Option(d.label||`音频输入 ${i+1}`,d.deviceId)));if([...$('input').options].some(o=>o.value===selected))$('input').value=selected;}
async function keepAwake(){try{if(running&&navigator.wakeLock)wake=await navigator.wakeLock.request('screen')}catch{}}
function frame(){if(!running)return;const data=new Float32Array(analyser.fftSize);analyser.getFloatTimeDomainData(data);const result=detectPitch(data,context.sampleRate);$('level').style.width=`${Math.min(100,result.rms*500)}%`;$('signalText').textContent=result.rms>.6?'音量过大':result.rms<.002?'等待拨弦':'正在聆听';if(result.frequency){lastGood=performance.now();history.push(result.frequency);if(history.length>5)history.shift();const sorted=[...history].sort((a,b)=>a-b),f=sorted[Math.floor(sorted.length/2)],reference=Number($('reference').value),info=noteInfo(f,reference),notes=presets[$('tuning').value];let target=info.midi,index=-1;if(notes){index=locked===null?notes.reduce((best,n,i)=>Math.abs(n-(69+12*Math.log2(f/reference)))<Math.abs(notes[best]-(69+12*Math.log2(f/reference)))?i:best,0):locked;target=notes[index];}const cents=1200*Math.log2(f/(reference*2**((target-69)/12))),good=Math.abs(cents)<=5; $('note').innerHTML=`${noteNames[target%12]}<small id="octave">${Math.floor(target/12)-1}</small>`;$('frequency').textContent=`${f.toFixed(1)} Hz`;$('reading').textContent=good?'已调准':`${cents<0?'偏低 · 调紧':'偏高 · 调松'} ${Math.abs(cents).toFixed(0)} 音分`;$('needle').style.left=`${50+Math.max(-50,Math.min(50,cents))*.96}%`;$('needle').style.opacity='1';document.querySelector('.display').classList.toggle('in-tune',good);document.querySelectorAll('.string').forEach((b,i)=>b.classList.toggle('active',i===index));}else if(performance.now()-lastGood>850)clearReading();timer=setTimeout(frame,75);}
async function stop(){running=false;clearTimeout(timer);stream?.getTracks().forEach(t=>t.stop());stream=null;if(context){await context.close().catch(()=>{});context=null;}await wake?.release().catch(()=>{});wake=null;$('start').classList.remove('running');$('start').innerHTML='开始调音 <span>●</span>';$('level').style.width='0%';$('signalText').textContent='已停止';clearReading();}
async function start(){if(!window.isSecureContext||!navigator.mediaDevices?.getUserMedia){$('status').textContent='需要通过 HTTPS 地址打开，才能使用麦克风。';$('httpsHelp').hidden=false;document.querySelector('details').open=true;return;}$('start').disabled=true;try{context=new (window.AudioContext||window.webkitAudioContext)();await context.resume();const id=$('input').value;stream=await navigator.mediaDevices.getUserMedia({audio:{...(id?{deviceId:{exact:id}}:{}),echoCancellation:false,noiseSuppression:false,autoGainControl:false},video:false});analyser=context.createAnalyser();analyser.fftSize=8192;analyser.smoothingTimeConstant=0;context.createMediaStreamSource(stream).connect(analyser);running=true;history=[];lastGood=0;$('start').classList.add('running');$('start').innerHTML='停止调音 <span>■</span>';$('status').textContent='正在聆听 · 每次只拨一根弦，稍等读数稳定';await devices().catch(()=>{});await keepAwake();frame();}catch(e){await stop();const messages={NotAllowedError:'麦克风未获授权，请在浏览器的网站设置中允许麦克风后重试。',NotFoundError:'未找到麦克风，请连接麦克风或声卡后重试。',NotReadableError:'无法读取麦克风，可能正被其他应用占用。',OverconstrainedError:'所选输入设备不可用，请选择系统默认麦克风。'};$('status').textContent=messages[e.name]||'无法启动音频，请检查输入设备后重试。';}finally{$('start').disabled=false}}
$('start').onclick=async()=>{if(running){await stop();$('status').textContent='已停止，麦克风已关闭。'}else await start()};$('input').onchange=async()=>{if(running){await stop();await start()}};
document.addEventListener('visibilitychange',()=>{if(document.hidden&&running){stop();$('status').textContent='已暂停，返回后点击开始调音。'}});window.addEventListener('pagehide',()=>{stream?.getTracks().forEach(t=>t.stop())});
renderStrings();if(!window.isSecureContext){$('connection').textContent='需要 HTTPS';$('httpsHelp').hidden=false;$('status').textContent='界面已就绪；麦克风需要使用 HTTPS 地址。';}
if('serviceWorker'in navigator&&window.isSecureContext)navigator.serviceWorker.register('./sw.js').catch(()=>{});
if(document.modelContext?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(document.modelContext.registerTool({name:'configure_guitar_tuning',description:'设置调弦方式和基准音；不会开启麦克风。',inputSchema:{type:'object',properties:{tuning:{type:'string',enum:['standard','dropd','flat','chromatic']},reference:{type:'number',enum:[432,440,442]}},required:['tuning','reference'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input){if(!input||!['standard','dropd','flat','chromatic'].includes(input.tuning)||![432,440,442].includes(input.reference)||Object.keys(input).some(k=>!['tuning','reference'].includes(k)))throw new Error('无效的调弦设置');$('tuning').value=input.tuning;$('reference').value=String(input.reference);$('tuning').onchange();$('reference').onchange();return {tuning:$('tuning').value,reference:Number($('reference').value),listening:running};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
